import requests as rqst

def Cryptolog():
    allCoins = 'BTC,ETH,XRP,BCH,LTC,DASH,XEM,NEO,XMR,MIOTA,ETC,LSK,ZEC,WAVES,STRAT,XLM,ARK,STEEM,EOS,GN'
    #,ADX,DGB,MTL,SWIFT,ETC,OK,XVG,VTC,ENRG,IOP,PIVX,CVC,ARDR,XMR,SC,XEM,MCO,SNT,PTOY,KORE,VRM,KMD,STORJ,VRC,STEEM,NAV,RDD,NMR,MAID,NXT,UNB,GNT,NXS,XZC,EDG,VIA,LMC,TRIG,DOGE,REP,RISE,GAME,BTS,AEON,SYS,GBYTE,TRST,EBST,FUN,XEL,BCY,NEOS,DCR,UBQ,EXCL,TKN,AGRS,VTR,SAFEX,LBC,IOC,FCT,SNRG,EXP,1ST,PINK,WINGS,BLK,EMC,MUE,SNGLS,RADS,CLOAK,LGD,GUP,ZEN,BLITZ,GNO,FLO,PART,GRC,CFI,GAM,MLN,ZCL,LUN,QRL,BAY,BNT,GOLOS,DCT,XCP,INFX,START,EFL,AMP,NLG,FLDC,ANT,VOX,UNO,MEME,BURST,MUSIC,RBY,ABY,GRS,NXC,TRUST,ERC,BITB,CRB,XAUR,RLC,ADT,DOPE,CLUB,NBT,PTC,DMD,QWARK,MYST,CANN,GEO,BLOCK,XST,HMQ,CRW,SHIFT,GLD,BYC,TKS,DTB,POT,XWC,COVAL,THC,TX,CURE,CPC,CLAM,SIB,GCR,PPC,XMG,BTCD,DGD,SYNX,FTC,TIME,SBD,PDC,EGC,ION,XDN,BRX,SLS,BTA,XMY,SLR,FAIR,XVC,APX,BRK,BSD,SWT,DRACO,SEQ,2GIVE,DYN,AUR,SPHR,BTC,LTC,ETH,NEO,OMG,XRP,BCC,ZEC,ETC,DASH,XMR'

    #,BTCD,BLOCK,GBYTE,LKK,REC,DGB,NXS,ETP,XVG,SYS,BDL,GXS,NXT,VEN,PURA,IOC,VTC,UBQ,PART,NAV,SPRTS,ATB,FAIR,NLG,RISE,RDD,CLAM,PPC,XZC,XEL,CLOAK,NLC2,AEON,VIA,EMC,DMD,XAS,NEBL,BAY,CMP,DCT,XCP,TCC,CRW,ION,EMC2,RBY,SIB,LEO,PPY,OMNI,SKY,NMC,MUE,GOLOS,OK,ECN,KORE,POT,SMART,MOON,PZM,EXP,SLS,ZEN,ENRG,BLK'
    request_string = rqst.get('https://min-api.cryptocompare.com/data/price?fsym=USD&tsyms='+allCoins)
    #request_string = rqst.get('https://min-api.cryptocompare.com/data/price?fsym=USD&tsyms=USD,BTC,BCH,ETH,LTC,LSK,NEO,XRP')
    coin_dict = request_string.json()
    print(coin_dict)
    return coin_dict

Cryptolog()
